
[[dependencies]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/api"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/appengine"
